### ISSUE TITLE
Support multilingual exhibits (translations and locale switching)

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#1912]
This is a feature/story ticket with the broad goal of enabling multilingual exhibits, meaning:

- Enable exhibit curators to provide translations of exhibit content (e.g., site title, menu labels, facet labels, feature and about page text) 
- Enable exhibit visitors to change languages and see any exhibit content that has been translated in that language

Specific tickets that are part of this feature:

- [x] #1911 - Enable exhibit admin to select available locales/languages 

- [ ] #1918 - Add and populate i18n locale file for Italian translations

- [x] #1920 - Add toggle for exhibit visitors to switch between languages (language selector)

- [x] #1914 - Enable curator to provide translations of general exhibit labels (title, subtitle, main menu items)

- [x] #1915 - Enable curator to provide translations of metadata field labels (labels, not metadata values)

- [x] #1916 - Enable curator to provide translations of search-related field labels (facets, sort fields)

- [x] #1917 - Enable curator to provide translations of browse category fields (title, description)

- [x] #1919 - Enable curator to provide translations of home, feature, and about page content (text content of widgets)

**Comment by ggeisler** [comment]
I'm closing this because the multilingual feature is done and the remaining item on the ticket checklist is not needed to demonstrate the completion of the feature (we used a Portuguese locale file rather than Italian, and the ticket for the Italian locale file will be handled in upcoming work).
