### ISSUE TITLE
Blacklight 7 / Bootstrap 4 bug punchlist

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/spotlight#2224]
- [x] Something's funny with the exhibit navbar contrast and hover states  (#2239 )
- [x] No glyphicons (#2230)
- [x] search_facet_url deprecation from Blacklight 7: https://github.com/projectblacklight/spotlight/pull/2231
- [x] Facet configuration page fixes #2234
- [x] Labels -> Badges (not too many) (#2235)
- [x] Tooltips appear to be broken (more obvious after #2230, but it's on the facet configuration page) (fixed downstream with https://github.com/sul-dlss/dlme/pull/672; ~not sure if there's a spotlight fix needed?~ fixed with #2252)
- [x] facet modals aren't working?
- [x] Curated Features dropdown in exhibit navbar (needs multiple published feature pages). 
  *  I noticed this in DLME and not Spotlight proper, but I imagine it exists upstream
- [x] modal headers are weird (#2250) 
- [x] Browse category drag handles are hidden #2251 
- [x] Edit saved searches - displays search params in a weird way (#2253)
- [x] Unpublished exhibits badge styling #2255 
- [x] Thumbnails too large in several widget edit panels #2264
- [x] ~~Widen search options select menu #2273~~
- [x] Text block for image-oriented widgets is always on right #2276
- [x] Suggested updates to Search results, List view #2283
- [x] Update styling of Feedback form #2290
