### ISSUE TITLE
Add new feature: Browse groups

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2562]
This is a story ticket for a new feature. These are the specific work tickets:

- [x] #2594 - Add tabs to Curation > Browse admin page
- [x] #2596 - Enable browse group creation and management
- [x] #2597 - Enable associating a browse category with a browse group 
- [x] #2567 - Display published browse groups as filters on Browse landing page

Not required to complete this new feature, but would take advantage of it:

- #2568 - Add a browse group widget to Exhibit item widgets

As an overview, the problem this proposed new feature addresses is that at Stanford we've found that some exhibits contain many browse categories and that subsets of those categories can relate to each other by theme. For example, in this exhibit: https://exhibits.stanford.edu/bacon/browse the exhibit curator prefixed the titles of browse categories "Farm workers:" and "Immigrants:" as a way to show which browse categories are related by theme. But since we show a flat list of all browse categories on the browse landing page, it is not as easy of it might be for the exhibit visitor to pick out themes of interest from a page with many browse categories.

The proposed browse group feature would enable the exhibit curator to **optionally** group browse categories into themes, or groups. The browse group feature can be ignored by exhibit curators who don't need it and the existing browse categories feature shouldn't be affected at all if browse groups are not used in an exhibit.

If an exhibit curator does want to use the browse groups feature, they would organize their browse categories into groups by first creating browse groups (ignore the callouts on the mockups below; they are referenced in the specific work tickets listed at the top of this comment):

<img width="766" alt="Browse groups tab - active groups" src="https://user-images.githubusercontent.com/101482/104525047-98c21180-55bc-11eb-9bb1-541b5e670c36.png">

---

And then associating a browse category with one or more browse groups:

<img width="788" alt="Group tab - groups checked" src="https://user-images.githubusercontent.com/101482/104525101-b68f7680-55bc-11eb-91c7-55972754101c.png">

---

When a browse group is published and contains child browse categories, the browse landing page shows a row of browse group filter buttons at the top. When the exhibit visitor selects a browse group filter, the browse landing page displays only the browse categories that belong to that browse group. For example, below the selected browse group is "Medium", which contains five browse categories:

<img width="991" alt="Screen Shot 2020-08-18 at 10 08 14 AM" src="https://user-images.githubusercontent.com/101482/90546671-3c5ae300-e13f-11ea-8e8c-7a0f7ab033f6.png">

**Comment by mejackreed** [comment]
All associated tasks have been completed. Note: #2607 has been spun out and we can address that when it needs to be prioritized.
