### ISSUE TITLE
Story: Add support for bulk actions through the exhibit UI

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/spotlight#2643]
This is a story ticket to group several more actionable tickets related to a new bulk actions feature. 

- [x] #2644: Modify curator view of search results page to offer new bulk actions button
- [x] #2645: Add bulk action: Change item visibility
- [x] #2647: Add bulk action: Add item tags
- [x] #2650: Add bulk action: Remove item tags
- TBD: Add bulk action: Update custom metadata field

As a summary, the goal of this feature is to enable the exhibit curator to update exhibit items in bulk, rather than one-by-one as they have to do now.

The bulk actions that we think will be useful:

- Change item visibility (public | private)
- Add item tags
- Remove item tags
- Update custom metadata field

There could be additional possible bulk actions in the future; the design should enable those to be added if and when they seem useful.

The proposed approach makes the following assumptions:

- A curator will access the bulk actions through a search result on the visitor side of the exhibit (i.e., the feature is not accessed through the admin UI). 

- Each of the available actions is applied to the entire search result set (i.e., there isn’t a separate page where the curator selects which items the action is applied to; instead the curator gathers the set of items the action is applied to by generating a search result with the desired items)

This approach is not necessarily the most flexible way for a curator to perform bulk actions (versus a dedicated page where the curator could select only the items they wanted the action applied to), but it is simpler and will be significantly easier to implement because we don't have to create an entirely new and likely somewhat complicated intermediary page.

<img width="1003" alt="Screen Shot 2021-02-03 at 3 47 04 PM" src="https://user-images.githubusercontent.com/101482/106820343-67c38280-6638-11eb-9d7d-edb066ac3117.png">

---

<img width="1003" alt="Screen Shot 2021-02-03 at 3 47 39 PM" src="https://user-images.githubusercontent.com/101482/106820370-727e1780-6638-11eb-87bd-92f35d17c244.png">

**Comment by mejackreed** [comment]
This epic has now been resolved with all linked tickets.
