### ISSUE TITLE
Enable image area selection

### ISSUE THREAD

**Issue by alundgard** [projectblacklight/spotlight#3185]
_This is a summary issue. As part of the Fall 2024 Work Cycle, Stanford Libraries intends to implement the following work regarding image area selection (“cropping”). We intend for some of this work to be done within Spotlight._

Instead of “crop” we use the terminology “select image area” to capture the multiple ways widgets display images. The Item Embed widget does not “crop” in the traditional sense.

- The Item Embed widget embeds an exhibit item in a viewer on a page. The embed viewer depends on the image source:
  - Images from Stanford Digital Repository are embedded in the sul-embed/Mirador viewer.
  - Images uploaded from Desktop are embedded in the OpenSeadragon viewer.
- Both views afford zooming and panning interactions.
- To enable “cropping” for these viewers, we will afford selecting an area of interest (zoom-level and focal point), so that creators can embed the viewer already-focused on a portion of the image.
- For example, this will allow the creator to specify the zoomed-in view (image below, right), rather than the default full-image view (image below, left), and should display the zoomed-in view when the exhibit page loads. The full image will be preserved, and the usual panning/zooming interactions will still be afforded.

<img width="1130" alt="mirador-zoom-focal-point" src="https://github.com/user-attachments/assets/fa933332-3f17-4491-b69a-061e8197a67d">

- For the non-Embed widgets (Item Row, Grid, Carousel, Slideshow) we will afford cropping functionality in the traditional sense, using the existing image cropping plugin.

## Task List
- [ ] Enable image area selection for Item Embed - Mirador
- [ ] Enable image area selection for non-Embed widgets
- [ ] Enable image area selection for Item Embed - OpenSeadragon

## Notes
The above issues draw from a few related issues:
- https://github.com/sul-dlss/exhibits/issues/357
- https://github.com/sul-dlss/exhibits/issues/2412
- https://github.com/sul-dlss/exhibits/issues/1002#issuecomment-381438825
